<a href="https://colab.research.google.com/github/shullaw/maths/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exploring Linear Algebra with numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 11, 22, 33, 6, 9, 12]).reshape(3, 3)
a

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 6,  9, 12]])

In [3]:
a.dtype

dtype('int64')

In [4]:
a.ndim

2

In [5]:
type(a)

numpy.ndarray

In [6]:
b = np.array([i for i in range(0, 18, 2)]).reshape(3, 3)
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [9]:
c = np.array([i for i in range(6)]).reshape(3, 2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

Matrix addition

In [10]:
def add_matrices(A, B):
  add = []

  for i in range(len(A)):
    add.append(A[i] + B[i])

  return np.array(add)


In [11]:
a.shape

(3, 3)

In [12]:
b.shape

(3, 3)

In [13]:
print('First matrix: \n', a)
print('\nSecond matrix: \n', b)
print('\nSum: \n', add_matrices(a, b))

First matrix: 
 [[ 1  2  3]
 [11 22 33]
 [ 6  9 12]]

Second matrix: 
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

Sum: 
 [[ 1  4  7]
 [17 30 43]
 [18 23 28]]


In [16]:
a + b  # numpy arrays of the same shape

array([[ 1,  4,  7],
       [17, 30, 43],
       [18, 23, 28]])

In [17]:
a - b

array([[ 1,  0, -1],
       [ 5, 14, 23],
       [-6, -5, -4]])

Dot Product
  - If A and B are both 1D: dot product (scalar result)
  - If A and B are both 2D: matrix multiplication
  - If A or B are scalar: element-wise multiplication
  - If A is n-D and B is m-D: sum-product

In [52]:
np.dot(a, b)

array([[1., 0.],
       [0., 1.]])

In [21]:
np.matmul(a, b)  # preferable to use with 2D matrices (or @ operator)

array([[ 48,  60,  72],
       [528, 660, 792],
       [198, 252, 306]])

Determinants and Transposing Matrices

In [23]:
a

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 6,  9, 12]])

In [24]:
det_a = np.linalg.det(a)
det_a

0.0

In [25]:
a.T

array([[ 1, 11,  6],
       [ 2, 22,  9],
       [ 3, 33, 12]])

In [26]:
np.transpose(a)

array([[ 1, 11,  6],
       [ 2, 22,  9],
       [ 3, 33, 12]])

Trace of a Matrix

In [27]:
a

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 6,  9, 12]])

In [28]:
np.trace(a)

35

In [29]:
symmetric_mat = a.dot(a.T)
symmetric_mat

array([[  14,  154,   60],
       [ 154, 1694,  660],
       [  60,  660,  261]])

In [32]:
symmetric_mat[1][2] == symmetric_mat[2][1]

True

In [33]:
diag_mat = np.zeros((3,3), dtype='int32')
np.fill_diagonal(diag_mat, 2)

diag_mat

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]], dtype=int32)

In [34]:
identity = np.zeros((3,3), dtype='float')
np.fill_diagonal(identity, 1)

identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
zero_mat = np.zeros((3,3))
zero_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Computing Inverse of Matrix

$AB = BA = I$

In [37]:
a = np.array([[2,3],
             [2,2]])
a

array([[2, 3],
       [2, 2]])

In [38]:
b = np.array([[-1, 1.5],
              [1, -1]])
b

array([[-1. ,  1.5],
       [ 1. , -1. ]])

In [39]:
a.dot(b)

array([[1., 0.],
       [0., 1.]])

In [40]:
inverse_a = np.linalg.inv(a)
inverse_a

array([[-1. ,  1.5],
       [ 1. , -1. ]])

In [41]:
inverse_a == b

array([[ True,  True],
       [ True,  True]])

In [42]:
a

array([[2, 3],
       [2, 2]])

In [43]:
b

array([[-1. ,  1.5],
       [ 1. , -1. ]])

In [48]:
a * b # element-wise

array([[-2. ,  4.5],
       [ 2. , -2. ]])

In [47]:
np.multiply(a, b)  # element-wise

array([[-2. ,  4.5],
       [ 2. , -2. ]])

In [49]:
a

array([[2, 3],
       [2, 2]])

In [50]:
b

array([[-1. ,  1.5],
       [ 1. , -1. ]])

In [51]:
a.shape, b.shape

((2, 2), (2, 2))

In [53]:
a.shape[1] == b.shape[0]

True

In [54]:
a.dot(b)

array([[1., 0.],
       [0., 1.]])

In [55]:
a @ b

array([[1., 0.],
       [0., 1.]])

In [56]:
from numpy.linalg import matrix_rank

In [57]:
matrix_rank(a)

2

In [58]:
from scipy.sparse import identity, diags

In [59]:
identity(2)

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements (1 diagonals) in DIAgonal format>

In [61]:
id_mat = identity(2).toarray()
id_mat

array([[1., 0.],
       [0., 1.]])

In [64]:
scalar_mat = diags([2,2,2], 0).toarray()  # 0 places on main diagonal
scalar_mat

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [66]:
diag_mat = diags([2, 1, 3], 0).toarray()  # toarray converts to numpy array
diag_mat

array([[2., 0., 0.],
       [0., 1., 0.],
       [0., 0., 3.]])

Matrix Decomposition

LU:

$L(Ux) = b \rightarrow Ux = L^{-1}b$

Full Pivot:

$PAQ = LU$

QR:

$A = QR$

$Q^T = Q^{-1}$

$Q^H = Q^{-1}$

$Q(Rx) = b \rightarrow Rx = Q^Tb = c \rightarrow Rx = c$

Cholesky: twice as efficient as LU for solving linear equations (only for Hermitian matrices)

Hermitian matrix: $A = AH$

Positive Definite Matrix: $z^TMz$ is positive for every non-zero real column vector $z$

$A = LL^{*}$

In [71]:
import numpy as np
from scipy.linalg import lu, qr, inv, cholesky


In [73]:
A = np.array([[4, 3],
             [6, 3]])
A

array([[4, 3],
       [6, 3]])

In [74]:
p, l, u = lu(A)

In [80]:
p  # permutation matrix

array([[0., 1.],
       [1., 0.]])

In [81]:
l  # lower triangular matrix

array([[1.        , 0.        ],
       [0.66666667, 1.        ]])

In [82]:
u  # upper triangular matrix

array([[6., 3.],
       [0., 1.]])

In [83]:
p @ l @ u  # np.matmul

array([[4., 3.],
       [6., 3.]])

In [84]:
np.allclose(p@l@u, A)

True

In [85]:
A = np.array([[2, 4, 6],
              [3, 6, 9],
              [1, 3, 5]])
A

array([[2, 4, 6],
       [3, 6, 9],
       [1, 3, 5]])

In [86]:
p, l, u = lu(A)

In [87]:
p

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [88]:
l

array([[1.        , 0.        , 0.        ],
       [0.33333333, 1.        , 0.        ],
       [0.66666667, 0.        , 1.        ]])

In [89]:
u

array([[3., 6., 9.],
       [0., 1., 2.],
       [0., 0., 0.]])

In [91]:
p.dot(l).dot(u)  # not as efficient as @

array([[2., 4., 6.],
       [3., 6., 9.],
       [1., 3., 5.]])

In [92]:
np.allclose(p.dot(l).dot(u), A)

True

In [93]:
A = np.array(np.random.randint(-10, 10, size=(3, 3)))
A

array([[ 6,  6, -6],
       [-8, -5, -8],
       [-6,  7, -3]])

In [95]:
q, r = qr(A)

In [96]:
q

array([[-0.51449576,  0.4466625 ,  0.73197454],
       [ 0.68599434, -0.297775  ,  0.66388389],
       [ 0.51449576,  0.84369583, -0.15320397]])

In [97]:
r

array([[-11.66190379,  -2.91547595,  -3.94446746],
       [  0.        ,  10.07472084,  -2.8288625 ],
       [  0.        ,   0.        ,  -9.24330641]])

In [98]:
q@r

array([[ 6.,  6., -6.],
       [-8., -5., -8.],
       [-6.,  7., -3.]])

In [99]:
np.allclose(q@r, A)

True

In [100]:
transpose_q = q.T
transpose_q

array([[-0.51449576,  0.68599434,  0.51449576],
       [ 0.4466625 , -0.297775  ,  0.84369583],
       [ 0.73197454,  0.66388389, -0.15320397]])

In [101]:
q @ transpose_q

array([[ 1.00000000e+00, -1.39716700e-17, -3.67157851e-17],
       [-1.39716700e-17,  1.00000000e+00,  1.34164607e-16],
       [-3.67157851e-17,  1.34164607e-16,  1.00000000e+00]])

In [102]:
inv_r = inv(r)
inv_r

array([[-0.08574929, -0.02481458,  0.04418682],
       [ 0.        ,  0.09925833, -0.03037746],
       [ 0.        ,  0.        , -0.1081864 ]])

In [103]:
r @ inv_r

array([[ 1.00000000e+00,  1.06305476e-17, -1.08759922e-17],
       [ 0.00000000e+00,  1.00000000e+00,  2.62830867e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [105]:
A = np.array(np.random.randint(-20, 20, size=(8, 4)))
A

array([[ -6,  13,  15,  18],
       [  8,   6,  13,  12],
       [ 19,   7, -10,  10],
       [-13, -11,   7,   1],
       [ 16, -12,  -6,   9],
       [-19,   4,   2,  -4],
       [ 16,  -4,  19,  10],
       [-13, -19,  -6,   6]])

In [106]:
q, r = qr(A)

In [109]:
q  # square matrix

array([[-0.1467348 , -0.45347508,  0.37107911, -0.63593599,  0.2358657 ,
        -0.32839599,  0.15280147, -0.20949969],
       [ 0.1956464 , -0.17466241,  0.38591844, -0.19084938, -0.13928879,
         0.26558736, -0.68605655,  0.43040377],
       [ 0.46466019, -0.17268488, -0.37085535, -0.43903682, -0.519066  ,
         0.29152657,  0.20136468, -0.17034917],
       [-0.31792539,  0.32557441,  0.31535073, -0.03276492, -0.43216285,
         0.09006673, -0.27257535, -0.65056211],
       [ 0.39129279,  0.45223662, -0.06969509, -0.28066584,  0.62646926,
         0.21133277, -0.19248988, -0.29079828],
       [-0.46466019, -0.19469745,  0.00614338, -0.04340409,  0.21233942,
         0.80846361,  0.21280996,  0.01651177],
       [ 0.39129279,  0.18504947,  0.68534214,  0.16984763, -0.07926808,
         0.15378548,  0.52733302,  0.0780452 ],
       [-0.31792539,  0.59276156, -0.04240844, -0.50579603, -0.15791318,
        -0.08120803,  0.17524988,  0.47716375]])

In [110]:
r  # upper triangular matrix

array([[ 40.8900966 ,   3.9373837 ,  -0.46466019,  11.42085832],
       [  0.        , -29.94155991,  -8.2103119 ,  -1.40379121],
       [  0.        ,   0.        ,  30.20554369,  13.86438393],
       [  0.        ,   0.        ,   0.        , -21.84884948],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ]])

In [111]:
np.allclose(q @ r, A)

True

In [112]:
A = np.matrix([[5, 3, 3],
               [3, 5, 2],
               [3, 2, 5]])
A

matrix([[5, 3, 3],
        [3, 5, 2],
        [3, 2, 5]])

In [114]:
AT = A.T
AT

matrix([[5, 3, 3],
        [3, 5, 2],
        [3, 2, 5]])

In [115]:
np.allclose(AT, A)

True

In [116]:
u = cholesky(A)
u

array([[2.23606798, 1.34164079, 1.34164079],
       [0.        , 1.78885438, 0.1118034 ],
       [0.        , 0.        , 1.78535711]])

In [117]:
u.T @ u

array([[5., 3., 3.],
       [3., 5., 2.],
       [3., 2., 5.]])

In [118]:
A

matrix([[5, 3, 3],
        [3, 5, 2],
        [3, 2, 5]])

In [119]:
np.allclose(u.T@u, A)

True

In [120]:
l = cholesky(A, lower=True)
l

array([[2.23606798, 0.        , 0.        ],
       [1.34164079, 1.78885438, 0.        ],
       [1.34164079, 0.1118034 , 1.78535711]])

In [121]:
l @ l.T

array([[5., 3., 3.],
       [3., 5., 2.],
       [3., 2., 5.]])

In [122]:
np.allclose(l@l.T, A)

True